version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.300-preview2-sdk-alpine
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build ./NetCore.sln
      - run: dotnet test NetCore.sln